FROM python:3.11

ENV PYTHONUNBUFFERED 1

COPY ./backend/requirements /requirements
COPY ./backend /app/backend
COPY ./.flake8 /.flake8

RUN python -m pip install --upgrade pip && \
    python -m pip install -r /requirements/dev.txt && \
    rm -rf /requirements && \
    adduser \
        --disabled-password \
        --no-create-home \
        django-user

USER django-user
WORKDIR /app