---
name: ci

on: [push]

jobs:
  test-list:
    name: Run linters and tests
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        run: docker-compose -f docker-compose-dev.yml run --rm django sh -c "flake8"
      - name: Test
        run: docker-compose -f docker-compose-dev.yml run --rm django sh -c "python backend/manage.py test"